version: '3.8'
services:
  jenkins: 
    build: .
    #privileged: true
    user: root
    ports:
    - 8080:8080
    - 50000:50000
    container_name: jenkins1
    volumes:
      - ./volumes/jenkins:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - docker_network
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - ./volumes/sonar/sonarqube_data:/opt/sonarqube/data
      - ./volumes/sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - ./volumes/sonar/sonarqube_logs:/opt/sonarqube/logs
    networks:
      - docker_network
  selenium:
    image: selenium/hub
    container_name: selenium
    ports:
    - "4442:4442"
    - "4443:4443"
    - "4444:4444"
    networks:
    - docker_network
  firefox:
    image: selenium/node-firefox
    container_name: firefox
    depends_on:
    - selenium
    environment:
    - SE_EVENT_BUS_HOST=selenium-env
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
    - docker_network

networks:
  docker_network:
    driver: bridge

      